version: 2
jobs:
  build:
    docker:
      - image: cimg/base:stable

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -qy make gcc libtool autoconf automake bison libreadline-dev

      - run:
          name: Autotools
          command: |
            libtoolize -qi
            autoreconf

      - run:
          name: Configure
          command: ./configure --with-readline

      - run:
          name: Build
          command: make 'ADDCFLAGS=-DGCDEBUG=1 -DREF_ASSERTIONS=1'

      - run:
          name: Test
          command: make trip
